<?php

return [
    "types" => [
        'Daire',
        'Residence',
        'Müstakil Ev',
        'Villa',
        'Çiftlik Evi',
        'Köşk & Konak',
        'Yalı',
        'Yalı Dairesi',
        'Yazlık',
    ],

    "room_counts" => [
        "Stüdyo (1+0)",
        "1+1",
        "1.5+1",
        "2+0",
        "2+1",
        "2.5+1",
        "2+2",
        "3+1",
        "3.5+1",
        "3+2",
        "4+1",
        "4.5+1",
        "4+2",
        "4+3",
        "4+4",
        "5+1",
        "5+2",
        "5+3",
        "5+4",
        "6+1",
        "6+2",
        "6+3",
        "7+1",
        "7+2",
        "7+3",
        "8+1",
        "8+2",
        "8+3",
        "8+4",
        "9+1",
        "9+2",
        "9+3",
        "9+4",
        "9+5",
        "9+6",
        "10+1",
        "10+2",
        "10 Üzeri",
    ],

    "building_age" => [
        "0",
        "1",
        "2",
        "3",
        "4",
        "5-10 arası",
        "11-15 arası",
        "16-20 arası",
        "21-25 arası",
        "26-30 arası",
        "31 ve üzeri",
    ],

    "floor_count_of_building" => [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30 ve üzeri",
    ],

    "floor_of_apartment" => [
        "Kot 4",
        "Kot 3",
        "Kot 2",
        "Kot 1",
        "Bodrum Kat",
        "Zemin Kat",
        "Bahçe Katı",
        "Giriş Katı",
        "Yüksek Giriş",
        "Müstakil",
        "Villa Tipi",
        "Çatı Katı",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30 ve üzeri",
    ],

    "heating" => [
        "Yok",
        "Soba",
        "Doğalgaz Sobası",
        "Kat Kaloriferi",
        "Merkezi",
        "Merkezi (Pay Ölçer)",
        "Doğalgaz (Kombi)",
        "Yerden Isıtma",
        "Klima",
        "Fancoil Ünitesi",
        "Güneş Enerjisi",
        "Jeotermal",
        "Şömine",
        "VRV",
        "Isı Pompası",
    ],

    "bathroom_count" => [
        "Yok",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "6 Üzeri",
    ],

    "current_state" => [
        "Boş",
        "Kiracılı",
        "Mülk Sahibi"
    ],

    "from_who" => [
        "Sahibinden",
        "Emlak Ofisinden",
        "İnşaat Firmasından",
        "Bankadan",
    ],
];
